[package]
name = "todomvc"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus-web = "0.3"
dioxus = "0.3"
im-rc = "15.0.0"

[profile.release]
lto = true
panic = "abort"
opt-level = 'z'
strip = "debuginfo"
codegen-units = 1
